export const CLIENTES: string[] = [
  'AEMSA',
  'AF STEELCASE STRAFOR s.a.',
  'ANDREU BARBERA, S.L.',
  'ARASAF INDUSTRIAL, S.L.',
  'ARNEG PORTUGUESA, Lda.',
  'ASTRA ILUMINACIÓN',
  'ASTURMADI DOORS, S.L.',
  'AVWEL SISTEMAS Y TRANSFORMACIÓN ELECTROMECÁNICA SA',
  'BEST TECH Tecnologia de Maq.',
  'Casals ventilación Air Industrial, S.L.',
  'Celux Iluminación, S.L.',
  'CLASS MANUFACTURING ,S.L.',
  'CORECO S.A.',
  'CROSSPRO, Lda.',
  'DIERRE IBERICA - Industria de Portas, S.A.',
  'DISTFORM S.L.',
  'DOCRILUC, S.L.',
  'Domingo Andreu, S.L.',
  'Dunia Cool Tech, Lda',
  'DYNAMOBEL',
  'EIB Electro Instaladora de Bairro, Lda',
  'Enimar 2006, S.L.',
  'EQUIPOS LAGOS S.A.',
  'EUN SISTEMAS, S.L.',
  'EURO FMP IMMOBILIARIA, S.L.',
  'EUROSHELVES - ESTANTES METALICAS, LDA',
  'EYPAR, S.A.',
  'FABRIGAS S.L.',
  'FAMO Indústria de Mobiliário de Escritório Lda.',
  'FIMEL, S.A.',
  'GARMALUX ILUMINACIÓN, S.L.',
  'GEINSA',
  'GPR IBÉRICA, S.A.U.',
  'GRUPEL SA',
  'GRUPO FORMA 5, S.L.',
  'Grupo Komtes',
  'GRUPO LUXIONA, S.L.',
  'GUIALMI Empresa de Móveis Metálicos, S.A.',
  'HAWORTH PORTUGAL s.a.',
  'HAWORTH PORTUGAL s.a. MOBILIARIO DE ESCRITORIO',
  'HILEX TRANSFORMACIONES METALICAS S.L.U.',
  'HIPUR, S.L.',
  'IDE ELECTRIC, S.L.',
  'IDUNA-Comércio e Indústria de Mobiliário,S.A.',
  'ILUCALFI, S.L.',
  'ILUSOL, S.A.',
  'IMECAL, S.A.',
  'INDUMECA - SOC. INDUSTRIAL METALÚRGICA DE BAIÃO, LDA',
  'INDUSTRIA TECNICA VALENCIANA SA',
  'INDUSTRIAL GRADHERMETIC S.A.E.',
  'INDUSTRIAL LABORUM IBERICA S.A.',
  'INDUSTRIAS GAMA, S.A.',
  'INDUSTRIAS MAM, S.A.',
  'Industrias Mecánicas Alcudia, S.L.',
  'Industrias Metalúrgicas de Patiño, S.L.',
  'INDUSTRIAS METALÚRGICAS PASCUAL S.L.',
  'INFRICO SUPERMARKET, S.L.',
  'INFRICO, S.L.',
  'ITV ICE MAKERS S.L.',
  'Josep Muntal, S.L.',
  'Lasergran S.L.',
  'Limobel Inwo, SL',
  'MAHENOR IBÉRICA, S.L.U.',
  'MAHENOR, S.L.',
  'MARSU S.L.',
  'MARTECH GROUP EQUIPMENTS, S.L.',
  'MATELCOMP Industria de Moldes e Componentes Plásticos, S.A.',
  'MEC. EJEA DE LOS CABALLEROS, S.L.',
  'MECANIZADO DE CHAPA TEKLAN, S.L.',
  'MECOS IBERICA, S.L.',
  'Metal Makers Barcelona, S.L.',
  'METALCUDIA, S.A.L.',
  'METALES Y FORMAS, S.L.',
  'Metálicas Criado, S.L.',
  'METALPERFIL, S.A.',
  'METALÚRGICA DO LEVIRA S.A.',
  'METALURGICA MANLLEUENSE, S.A.',
  'MOBEL LINEA',
  'MOSTOLES INDUSTRIAL S.A.',
  'NAVARRETE E HIJOS s.a.',
  'NOVOFERM ALSAL S.A.',
  'NUEVAS LINEAS DE EXTINCION, S.L.',
  'ODEL-LUX, S.A.',
  'OFITA INTERIORES, S.A.',
  'Onnera Group S. Coop.',
  'Onnera Refrigeration, S.A.',
  'Ormazabal y Compañía, S.L.U.',
  'ORNALUX s.a.',
  'ORONA S. COOP.',
  'OSCAR ZARZOSA, S.A.',
  'OXIEBRO, S.L.',
  'PECAR, S.A.',
  'PEDRO BRENHA, LDA',
  'PHILIPS IBERICA S.A.',
  'PLEGUIN METAL, S.L.',
  'Ponce Tecnología Industrial S.L.',
  'PREBUILD.PT- Investimentos, LDA',
  'PRESTIMAC - Moldes Cunhos e Cortantes, Lda',
  'PROTOLASER, S.L.',
  'PUERTAS PADILLA S.L.',
  'PUERTAS ROPER S.L.',
  'PUNZOMET S.L.',
  'RAIO - MOVÉIS METÁLICOS, LDA',
  'RALL - MOBILIÁRIO E SOLUÇÕES PARA ESCRITÓRIO, S.A.,',
  'RAMALHOS, S.A.',
  'REM - IRU, S.L.',
  'RIBO FIRE SYSTEMS, S.L.',
  'RST-CONSTRUTORA DE MÁQUINAS E ACESSÓRIOS SA',
  'RUEDAS ROAR, S.A.',
  'SALVA INDUSTRIAL S.L.',
  'SALVAGNINI IBÉRICA S.L.',
  'SALVAGNINI ITALIA S.p.A.',
  'SANDOMETAL - METALOMECÂNICA E AR CONDICIONADO, SA',
  'SARRALLE MUEBLES METALICOS, S.L.',
  'SCHINDLER DRIVE SYSTEMS',
  'SCHNEIDER ELECTRIC ESPANA, S.A.U.',
  'SELOPIN, S.L.U.',
  'SETROC Manufacturas Metálicas, S.L.',
  'SME S.A.',
  'SOLZAIMA Equipamentos para energias renováveis SA',
  'Steel Lockers, S.L.',
  'STINSER INGENIERIA Y TRANSFORMADOS S.L.U.',
  'STinser Suministros Integrales del Acero SL',
  'TAFAME, S.A.U.',
  'TALLERES GAPA, S.L.',
  'TAUX VALLES, S.L.',
  'TECNICHAPA, S.L.U.',
  'TECNICUADRO S.A.',
  'TECNOLAMA S.A.',
  'TECNOVEN',
  'TERRALLUM, S.L.',
  'THU Perfil S.L.',
  'TK Elevator Manufacturing Spain, SLU',
  'TRANSFORMADOS METÁLICOS RICARTE CASAREJOS S.L.U',
  'TROX ESPAÑOLA',
  'VARISOM CONTROLO ELECTRÓNICO, LDA',
  'VILAPLANA s.a.',
  'VILLA ESTANTERIAS METALICAS , S.L.',
  'YUDIGAR, S.L.',
];
